package cdkdmsreplication


// DMS replication instance class.
// See: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.Types.html
//
type ReplicationInstanceClass string

const (
	ReplicationInstanceClass_T3_MICRO ReplicationInstanceClass = "T3_MICRO"
	ReplicationInstanceClass_T3_SMALL ReplicationInstanceClass = "T3_SMALL"
	ReplicationInstanceClass_T3_MEDIUM ReplicationInstanceClass = "T3_MEDIUM"
	ReplicationInstanceClass_T3_LARGE ReplicationInstanceClass = "T3_LARGE"
	ReplicationInstanceClass_C5_LARGE ReplicationInstanceClass = "C5_LARGE"
	ReplicationInstanceClass_C5_XLARGE ReplicationInstanceClass = "C5_XLARGE"
	ReplicationInstanceClass_C5_2XLARGE ReplicationInstanceClass = "C5_2XLARGE"
	ReplicationInstanceClass_C5_4XLARGE ReplicationInstanceClass = "C5_4XLARGE"
	ReplicationInstanceClass_C5_9XLARGE ReplicationInstanceClass = "C5_9XLARGE"
	ReplicationInstanceClass_C5_12XLARGE ReplicationInstanceClass = "C5_12XLARGE"
	ReplicationInstanceClass_C5_18XLARGE ReplicationInstanceClass = "C5_18XLARGE"
	ReplicationInstanceClass_C5_24XLARGE ReplicationInstanceClass = "C5_24XLARGE"
	ReplicationInstanceClass_C6I_LARGE ReplicationInstanceClass = "C6I_LARGE"
	ReplicationInstanceClass_C6I_XLARGE ReplicationInstanceClass = "C6I_XLARGE"
	ReplicationInstanceClass_C6I_2XLARGE ReplicationInstanceClass = "C6I_2XLARGE"
	ReplicationInstanceClass_C6I_4XLARGE ReplicationInstanceClass = "C6I_4XLARGE"
	ReplicationInstanceClass_C6I_8XLARGE ReplicationInstanceClass = "C6I_8XLARGE"
	ReplicationInstanceClass_C6I_12XLARGE ReplicationInstanceClass = "C6I_12XLARGE"
	ReplicationInstanceClass_C6I_16XLARGE ReplicationInstanceClass = "C6I_16XLARGE"
	ReplicationInstanceClass_C6I_24XLARGE ReplicationInstanceClass = "C6I_24XLARGE"
	ReplicationInstanceClass_C6I_32XLARGE ReplicationInstanceClass = "C6I_32XLARGE"
	ReplicationInstanceClass_C7I_LARGE ReplicationInstanceClass = "C7I_LARGE"
	ReplicationInstanceClass_C7I_XLARGE ReplicationInstanceClass = "C7I_XLARGE"
	ReplicationInstanceClass_X7I_2XLARGE ReplicationInstanceClass = "X7I_2XLARGE"
	ReplicationInstanceClass_X7I_4XLARGE ReplicationInstanceClass = "X7I_4XLARGE"
	ReplicationInstanceClass_X7I_8XLARGE ReplicationInstanceClass = "X7I_8XLARGE"
	ReplicationInstanceClass_X7I_12XLARGE ReplicationInstanceClass = "X7I_12XLARGE"
	ReplicationInstanceClass_X7I_16XLARGE ReplicationInstanceClass = "X7I_16XLARGE"
	ReplicationInstanceClass_X7I_24XLARGE ReplicationInstanceClass = "X7I_24XLARGE"
	ReplicationInstanceClass_X7I_48XLARGE ReplicationInstanceClass = "X7I_48XLARGE"
	ReplicationInstanceClass_R5_LARGE ReplicationInstanceClass = "R5_LARGE"
	ReplicationInstanceClass_R5_XLARGE ReplicationInstanceClass = "R5_XLARGE"
	ReplicationInstanceClass_R5_2XLARGE ReplicationInstanceClass = "R5_2XLARGE"
	ReplicationInstanceClass_R5_4XLARGE ReplicationInstanceClass = "R5_4XLARGE"
	ReplicationInstanceClass_R5_8XLARGE ReplicationInstanceClass = "R5_8XLARGE"
	ReplicationInstanceClass_R5_12XLARGE ReplicationInstanceClass = "R5_12XLARGE"
	ReplicationInstanceClass_R5_16XLARGE ReplicationInstanceClass = "R5_16XLARGE"
	ReplicationInstanceClass_R5_24XLARGE ReplicationInstanceClass = "R5_24XLARGE"
	ReplicationInstanceClass_R6I_LARGE ReplicationInstanceClass = "R6I_LARGE"
	ReplicationInstanceClass_R6I_XLARGE ReplicationInstanceClass = "R6I_XLARGE"
	ReplicationInstanceClass_R6I_2XLARGE ReplicationInstanceClass = "R6I_2XLARGE"
	ReplicationInstanceClass_R6I_4XLARGE ReplicationInstanceClass = "R6I_4XLARGE"
	ReplicationInstanceClass_R6I_8XLARGE ReplicationInstanceClass = "R6I_8XLARGE"
	ReplicationInstanceClass_R6I_12XLARGE ReplicationInstanceClass = "R6I_12XLARGE"
	ReplicationInstanceClass_R6I_16XLARGE ReplicationInstanceClass = "R6I_16XLARGE"
	ReplicationInstanceClass_R6I_24XLARGE ReplicationInstanceClass = "R6I_24XLARGE"
	ReplicationInstanceClass_R6I_32XLARGE ReplicationInstanceClass = "R6I_32XLARGE"
	ReplicationInstanceClass_R7I_LARGE ReplicationInstanceClass = "R7I_LARGE"
	ReplicationInstanceClass_R7I_XLARGE ReplicationInstanceClass = "R7I_XLARGE"
	ReplicationInstanceClass_R7I_2XLARGE ReplicationInstanceClass = "R7I_2XLARGE"
	ReplicationInstanceClass_R7I_4XLARGE ReplicationInstanceClass = "R7I_4XLARGE"
	ReplicationInstanceClass_R7I_8XLARGE ReplicationInstanceClass = "R7I_8XLARGE"
	ReplicationInstanceClass_R7I_12XLARGE ReplicationInstanceClass = "R7I_12XLARGE"
	ReplicationInstanceClass_R7I_16XLARGE ReplicationInstanceClass = "R7I_16XLARGE"
	ReplicationInstanceClass_R7I_24XLARGE ReplicationInstanceClass = "R7I_24XLARGE"
	ReplicationInstanceClass_R7I_48XLARGE ReplicationInstanceClass = "R7I_48XLARGE"
)

